apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments-service-backend-svc
  name: payments-service-backend-svc
spec:
  type: NodePort
  ports:
    - port: 8003
      targetPort: 8003
      nodePort: 30003
  selector:
    app: payments-service-backend

