apiVersion: v1
kind: Service
metadata:
  labels:
    app: production-service-backend-svc
  name: production-service-backend-svc
spec:
  type: NodePort
  ports:
    - port: 8003
      targetPort: 8003
      nodePort: 30004
  selector:
    app: production-service-backend

