apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: production-service-backend-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Pod
    name: production-service-backend
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80