apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: production-service-backend-deployment
  name: production-service-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: production-service-backend
  template:
    metadata:
      labels:
        app: production-service-backend
    spec:
      containers:
        - env:
            - name: postgre.address
              value: postgres
          image: erich852/production-service
          name: production-service-project
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
              protocol: TCP
          resources:
            requests:
              cpu: 1m
      restartPolicy: Always
