name: Deploy to ECR

on:
  push:
    branches: [ main ]

env:
  EKS_CLUSTER_NAME: apps_cluster
  AWS_REGION: us-east-1

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:

      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: https://registry.hub.docker.com/v2/
          IMAGE_TAG: erich852/production:latest
        run: |          
          kubectl apply -f manifests/postgres-service.yaml
          kubectl apply -f manifests/postgres-deployment.yaml
          kubectl apply -f manifests/postgres-data-persistentvolumeclaim.yaml
          kubectl apply -f manifests/production-service-backend-service.yaml
          kubectl apply -f manifests/production-service-backend-deployment.yaml
          kubectl apply -f manifests/production-service-backend-autosacling.yaml
